#
#
#version: "3.8"
#
#services:
#  mongoDB:
#    image: mongo
#    container_name: post-service
#    ports:
#      - "27017:27017"
#    volumes:
#      - data:/data
#
#
#
#
#volumes:
#  data: {}












